### ISSUE TITLE
Change 'Delete' To 'Retire' and Add 'Retirement' page 

### ISSUE THREAD

**Issue by robertfmurdock** [robertfmurdock/Coupling#11]
All currently retired players should be visible on the Retirement page and be able to be restored to the team from there.

**Comment by jfolkerth** [comment]
There's a new endpoint and component for this. Still needs to be wired up to navigation in some way. I was thinking of just adding the tribe card for return navigation like on the history page. The current pairings page would have a "View retired players" button.

**Comment by jfolkerth** [comment]
Created navigation for the route and updated the UI. Started on a way to resurrect retired players but didn't finish.

**Comment by robertfmurdock** [comment]
Yay!

**Comment by robertfmurdock** [comment]
Looks complete for now, closing issue.
