### ISSUE TITLE
Give me an error when tribe creation fails

### ISSUE THREAD

**Issue by jfolkerth** [robertfmurdock/Coupling#17]
If I fail to put in all required tribe information, a new tribe will not be created, I am navigated to a different screen, and no error message is displayed. It is unclear what fields are required, so I don't know what to fix or even what went wrong.

Desired behavior: When I navigate to the tribe creation screen, I can identify which fields are required. When I fail to give all required tribe information, I stay on the same screen and receive an error message detailing why creating the tribe failed.

**Comment by robertfmurdock** [comment]
Should be resolved now - tribe ids are now generated, so it is far more difficult to run into this.
