### ISSUE TITLE
Google Authentication Not Working

### ISSUE THREAD

**Issue by dougcyporyn** [robertfmurdock/Coupling#28]
Repeatedly asked to sign in rather than being authenticated

**Comment by robertfmurdock** [comment]
Thanks for the intel - is this something that started recently? Or is this your first time using the app

**Comment by dougcyporyn** [comment]
Thank you for the quick response. We have been using this awesome pairing app for quite some time. Tried assigning pairs after stand-up today and was unable to sign in. Cleared all cookies, restarted browser, same issue. Tried in Chrome and Firefox. Others on my team also unable to access.

**Comment by robertfmurdock** [comment]
Glad its working for you but super sorry that happened! I’ll take a look at Auth0 over lunch and hopefully things can get resolved.

**Comment by robertfmurdock** [comment]
Because of cookie lifetimes I imagine it could be tricky, but do you know the last time you successfully logged in?

**Comment by robertfmurdock** [comment]
Hm, I’ve gone through the authentication flow in incognito mode three times now and it appears to be working for me following these steps:

- new incognito window
- click through to the auth0 frame
- click through to google
- authenticate with google
- redirected to the tribe list


Does that work for you in incognito or is that a problem?

**Comment by robertfmurdock** [comment]
I think I've accidentally reproduced the issue on one of my other machines 😅. More to come.

**Comment by robertfmurdock** [comment]
This looks like it affects specific accounts, as some of my emails work, and others do not. For worse, I've been using emails that work for my testing lately 🙃

I can confirm it happens after Auth0 confirms that the account is good, and the error is on Coupling's side.

My bad! Still investigating what is the root cause.

**Comment by robertfmurdock** [comment]
Ok, I believe I’ve found it:

Here’s the fix, including a test that should (hopefully) prevent the specific issue from recurring.

https://github.com/robertfmurdock/Coupling/commit/b627363b37acee27b6a3b4065af362f25af542db

If all goes well, it should deploy in 20 minutes or so. Help is on the way!

- Rob

**Comment by robertfmurdock** [comment]
(deploying is taking longer than expected for reasons related to the memory availability of CircleCI jobs on the free tier, so its not actually deployed yet 😅)

**Comment by dougcyporyn** [comment]
Hi Rob, just getting caught up here. Thanks for the speedy attention and troubleshooting! Please let me know if there is anything I can do to help!

**Comment by robertfmurdock** [comment]
After this job is done, give it another shot and let me know if your issue is resolved. :) That would help tremendously.

Hopefully you can see this, AFAIK the job progress is public

https://app.circleci.com/pipelines/github/robertfmurdock/Coupling/3909/workflows/ee3a2669-c6b1-4f78-91fc-2a6555b979bb

**Comment by robertfmurdock** [comment]
should be about 10 minutes from now, either way.

**Comment by robertfmurdock** [comment]
The user I reproduced the issue with appears to be working again. Can you confirm on your side?

**Comment by dougcyporyn** [comment]
Its working!! Thank you SO much! Dev team will be happy to rotate pairs tomorrow and we don't have to FAKE it. :)

**Comment by robertfmurdock** [comment]
Haha that’s fantastic news. :)

It warms my heart to hear that your team finds it useful. Thanks so much for reaching out, and sorry again about the hiccup!

**Comment by dougcyporyn** [comment]
Hey, no worries! Super happy you were able to fix it so fast. We use your app every Monday at the end of stand-up. It's awesome. Thanks for making it available and providing support
